### PR TITLE
Institution user approval

### PR DESCRIPTION
**Pull request by rantahar**
Allow institution to choose whether they require users to be approved. If not, most functionality is available to unapproved users. These users are approved automatically when they become members of a project with an approved allocation. They get a username on the cluster at this point

### CODE REVIEW

**Comment by rantahar** [comment]
Adresses issue #22

**Comment by edbennett** [comment]
I'm inclined to keep this week's new features as a separate branch and PR them separately, to avoid confusing the review process on the phase-2 PR.

**Comment by rantahar** [comment]
Ok, that's probably better

**Comment by edbennett** [comment]
I'm confused reading this code—is needs_user_approval True for the old workflow or the new one? If the latter, then would "auto_user_approval" be a better name?

**Comment by rantahar** [comment]
needs_user_approval is True for the old workflow and False for the new one.

**Pull request closed without merging**
